version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3334:3334"
    environment:
      - DATABASE_URL=file:./dev.db
      - PORT=3334
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    volumes:
      - ./prisma:/app/prisma
      - db-data:/app/prisma
    restart: unless-stopped

volumes:
  db-data:
